import { useEffect, useMemo, useState } from "react";
import { createMachine, createRevision } from "../api/machines";
import { getIngestionJob, integrateKnowledge, retryIngestionJob, uploadManual } from "../api/client";
const sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
function parseStage(stage=""){const p=stage.split("|");const percent=Number.isFinite(Number(p[1]))?Number(p[1]):(stage.startsWith("completed")?100:0);return {percent:Math.max(0,Math.min(100,percent)),label:p[2]||p[0]||"Queued"};}
function bytes(n){if(!n)return"0 B";const u=["B","KB","MB","GB"];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),3);return `${(n/1024**i).toFixed(i?1:0)} ${u[i]}`;}
export default function MachineOnboarding({onReady,onCancel}){
 const [form,setForm]=useState({manufacturer:"",family:"",model:"",revision:"Rev A"}); const [file,setFile]=useState(null); const [busy,setBusy]=useState(false); const [job,setJob]=useState(null); const [stage,setStage]=useState("Ready to upload"); const [error,setError]=useState(""); const [upload,setUpload]=useState(0); const [uploadBytes,setUploadBytes]=useState({loaded:0,total:0}); const [processing,setProcessing]=useState(0);
 const update=(k,v)=>setForm(x=>({...x,[k]:v}));
 async function watch(jobId){for(;;){const j=await getIngestionJob(jobId);setJob(j);const s=parseStage(j.stage);setProcessing(j.percent ?? s.percent);setStage(j.stage_label || s.label);if(j.status==="completed")return j;if(j.status==="failed")return j;await sleep(900);}}
 async function retry(){if(!job)return;setBusy(true);setError("");try{const j=await retryIngestionJob(job.job_id);setJob(j);setStage("Retry queued — resuming from saved checkpoint…");const done=await watch(j.job_id);if(done.status==="failed")setError(done.error_message||"Ingestion failed again.");else await finish(done);}catch(e){setError(e.message||"Retry failed.");}finally{setBusy(false);}}
 async function finish(done){setStage("Building machine knowledge…");try{await integrateKnowledge(done.revision_id || job?.revision_id);}catch(e){/* integration is separate; ingestion is still successful */} onReady({productId:job?.product_id,revisionId:job?.revision_id});}
 async function submit(e){e.preventDefault();if(!form.manufacturer.trim()||!form.family.trim()||!form.model.trim()||!form.revision.trim()||!file){setError("Enter the machine details and select a PDF manual.");return;}setBusy(true);setError("");setJob(null);setUpload(0);setProcessing(0);try{setStage("Creating machine…");const product=await createMachine({manufacturer:form.manufacturer.trim(),family:form.family.trim(),model:form.model.trim()});setStage("Creating revision…");const revision=await createRevision(product.id,{label:form.revision.trim()});setStage("Uploading PDF…");const j=await uploadManual({revisionId:revision.id,file,title:file.name,idempotencyKey:`${revision.id}:${file.name}:${file.size}:${file.lastModified}`,onUploadProgress:({loaded,total,percent})=>{setUpload(percent);setUploadBytes({loaded,total});}});setUpload(100);setUploadBytes({loaded:file.size,total:file.size});setJob({...j,revision_id:revision.id,product_id:product.id});const done=await watch(j.job_id);if(done.status==="failed"){setError(done.error_message||"Ingestion failed.");return;}setStage("Building machine knowledge…");try{await integrateKnowledge(revision.id);}catch{}onReady({productId:product.id,revisionId:revision.id,product,revision});}catch(e){setError(e.message||"Unable to onboard machine.");}finally{setBusy(false);}}
 const uploadText=useMemo(()=>file?`${file.name} · ${bytes(file.size)}`:"Choose a PDF manual",[file]); const overall=upload<100?Math.round(upload*.35):Math.round(35+processing*.65); const failed=job?.status==="failed"; const ready=job?.status==="completed";
 return <div className="onboarding-overlay"><form className="onboarding-card" onSubmit={submit}><div className="eyebrow">MACHINE ONBOARDING</div><h2>Bring a machine into Crater.</h2><p className="muted">Upload the manual, build machine knowledge, and make ingestion resumable if anything fails.</p><div className="onboarding-grid"><label>Manufacturer<input value={form.manufacturer} onChange={e=>update("manufacturer",e.target.value)} placeholder="e.g. Mitsubishi Electric" disabled={busy}/></label><label>Product family<input value={form.family} onChange={e=>update("family",e.target.value)} placeholder="e.g. M800V" disabled={busy}/></label><label>Model<input value={form.model} onChange={e=>update("model",e.target.value)} placeholder="e.g. M850VW" disabled={busy}/></label><label>Revision<input value={form.revision} onChange={e=>update("revision",e.target.value)} placeholder="e.g. Ver. M" disabled={busy}/></label></div><label className="file-drop">Service / technical manual (PDF)<input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)} disabled={busy||!!job}/><span>{uploadText}</span></label>{(busy||job)&&<div className={`ingestion-progress-panel status-${failed?"failed":ready?"ready":"processing"}`}><div className="progress-heading"><span>{failed?"Ingestion failed":ready?"Ingestion ready":stage}</span><strong>{ready?100:overall}%</strong></div><div className="progress-track"><div className="progress-fill" style={{width:`${ready?100:overall}%`}}/></div><div className="progress-details"><div><span className={upload>=100?"step done":"step live"}>●</span><span>PDF upload</span><strong>{upload}%</strong></div><div><span className={processing>=100?"step done":processing>0?"step live":"step"}>●</span><span>Manual processing</span><strong>{processing}%</strong></div></div>{uploadBytes.total>0&&upload<100&&<div className="progress-subtext">{bytes(uploadBytes.loaded)} / {bytes(uploadBytes.total)} uploaded</div>}{job?.ocr_warning&&<div className="progress-subtext">⚠ {job.ocr_warning}</div>}{failed&&<><div className="diag-error">{job.error_message||error||"The pipeline stopped. Your uploaded PDF is retained."}</div><div className="onboarding-actions"><button type="button" className="primary-button" onClick={retry} disabled={busy}>Retry from saved checkpoint</button></div></>}{ready&&<div className="progress-subtext">✓ PDF retained · ✓ ingestion complete · machine is ready for diagnosis</div>}</div>}{error&&!failed&&<div className="diag-error">{error}</div>}<div className="onboarding-actions"><button type="button" onClick={onCancel} disabled={busy}>Cancel</button>{!failed&&<button className="primary-button" type="submit" disabled={busy||ready}>{ready?"Ready":"Upload & start diagnosis"}</button>}</div></form></div>;
}
